### ISSUE TITLE
Unhandled Rejection (Error): Invalid state

### ISSUE THREAD

**Issue by daviseford** [auth0/auth0-spa-js#245]
### Description

I am having this problem currently:

When users "Continue with Google", auth0 fails in the background with the following error
```
Uncaught (in promise) Error: Invalid state
    at t.<anonymous> (auth0-spa-js.production.js:1712)
    at auth0-spa-js.production.js:152
    at Object.next (auth0-spa-js.production.js:100)
    at auth0-spa-js.production.js:72
    at new Promise (<anonymous>)
    at i (auth0-spa-js.production.js:49)
    at t.handleRedirectCallback (auth0-spa-js.production.js:1698)
    at react-auth0-wrapper.js:27
    at l (runtime.js:45)
    at Generator._invoke (runtime.js:264)
```

My app is set up using the React Quick Start instructions with no modifications to anything auth0-related. I am using `"@auth0/auth0-spa-js": "1.3.1"`

The error only occurs when using the "Continue with Google" option. I can verify that the URL contains a `?code=nCniVKWi7AeavwQQ&state=ZjFfWU5nLkVISFhtN2RQOWF0ZENnRjZUNm00UDZpa3RHN2hCX0c1Z1V4Yw%3D%3D#` value

I read #68 and it wasn't helpful, so I've created a new ticket.

### Reproduction

1. Click "Log In"
2. "Continue with Google"
3. Upon return to the application, the error occurs in the console.
4. This happens in DEV environment (localhost) and production (a site with SSL enabled)

### Environment

> Please provide the following:

- **Version of this library used:** `"@auth0/auth0-spa-js": "1.3.1"`
- **Version of the platform or framework used, if applicable:** React Quick Start in a CreateReactApp app
- **Other relevant versions (language, server software, OS, browser):** Chrome (desktop, iOS, Android)
- **Other modules/plugins/libraries that might be involved:** n/a

**Comment by daviseford** [comment]
I will switch to my own keys and report back!

**Comment by daviseford** [comment]
If you want to see this in action, pull down https://github.com/daviseford/aos-reminders , run `yarn start`, and click Log In

**Comment by daviseford** [comment]
I also tried the Firefox fix suggested in the FAQ for the hell of it - no dice :)

**Comment by luisrudge** [comment]
Thanks for your patience with this! I have just a few more questions:
- Does it happen if you use other social connection (like Twitter or Facebook)?
- Would you mind sending a HAR file to luis.rudge at auth0.com (please be aware of potential secrets/passwords)? I'll investigate what's going on.

**Comment by daviseford** [comment]
Sent you an email. I will try Twitter shortly.

**Comment by daviseford** [comment]
Twitter worked fine. I don't use Facebook so I can't test that out.

**Comment by CueToDo** [comment]
I've been looking at this issue on and off for a few days, checking Auth0 application setup, but can't get around Invalid State error

`core.js:6014 ERROR Error: Invalid state
    at t.<anonymous> (auth0-spa-js.production.js:1)
    at auth0-spa-js.production.js:1
    at Object.next (auth0-spa-js.production.js:1)
    at auth0-spa-js.production.js:1
    at new ZoneAwarePromise (zone-evergreen.js:876)
    at r (auth0-spa-js.production.js:1)
    at t.handleRedirectCallback (auth0-spa-js.production.js:1)
    at MergeMapSubscriber.project (auth.service.ts:33)
    at MergeMapSubscriber._tryNext (mergeMap.js:46)
    at MergeMapSubscriber._next (mergeMap.js:36)`

I've used the Quick Start example unmodified and have also cloned from GitHub, plugging in my clientId and domain.

I've updated to 1.3.1
@auth0/auth0-spa-js": "^1.3.1",

Application is Angular SPA (Angular: 8.2.10)

Error on Facebook only. Google and Twitter are OK

I created a new tenant and redirect on callback worked fine first time only.  

On subsequent logins the redirect fails. App remains on callback page with spinner: 

http://localhost:3000/callback?code=xxx&state=yyy

I am logged in - clicking the login button again displays profile pic and allows me to go to profile page. Just not getting to this.router.navigate([targetRoute]); in handleAuthCallback

I've cleared all cookies for localhost, then for all sites, but the problem persists.

Given that login worked first time on the new tenant suggests data is being cached somewhere so that redirect on subsequent login fails.

What is state being validated against?

**Comment by danielres** [comment]
I am experiencing the exact same issue in my app which is using parcel.

When I run the [official example](https://github.com/auth0-samples/auth0-react-samples): all works fine on my machine.

I ported the official example with minimal changes to parcel, the problem appears.

I published my modified example here: https://github.com/danielres/auth0-parcel-problem-example

First thing that comes in mind is that maybe `@auth0/auth0-spa-js` is using some modern JS feature which is supported by `create-react-app` out of the box, but not by parcel. WDYT?

**Comment by danielres** [comment]
notes: 

- I'm not using Auth0 development keys, but my own keys.
- Same problem in Chrome and Firefox
- I haven't tried other types of login (twitter, ...). Only Google.

Hope the example repo will help to find the issue.

**Comment by brunolazzaro** [comment]
Having a similar issue. No problems logging in with other connections but when using Facebook we get "Invalid State" back. 

We're bundling the code with webpack and it looks like when importing the library it's pulling in the minified prod version, so maybe the double minification could be an issue?

**Comment by luisrudge** [comment]
@danielres does it work when you use this SDK in development mode (before parcel minifies the bundle)?

**Comment by danielres** [comment]
@luisrudge I'm not 100% sure what you mean by "use this SDK in development mode".
I'm new to parcel, so I'm not sure if there are some options I missed.

So far, I've only tried locally, on my laptop, with `NODE_ENV=development`.
This means parcel was working in development mode.
I don't think parcel minifies anything in this case, but I might be wrong.

**Comment by AntoLepejian** [comment]
I too always get invalid state i've opened an issue [here](https://github.com/auth0-samples/auth0-react-samples/issues/161) because even the sample application causes the same problem

**Comment by AntoLepejian** [comment]
> I too always get invalid state i've opened an issue [here](https://github.com/auth0-samples/auth0-react-samples/issues/161) because even the sample application causes the same problem

I just tried github and it worked perfectly, google and facebook login however always cause an invalid state error exception to be raised

**Comment by stevehobbsdev** [comment]
@AntoLepejian Are you able to confirm if your scenario works with a previous version of the SDK < 1.3.0 (1.2.3, for example)?

**Comment by AntoLepejian** [comment]
@stevehobbsdev  hey, I only just added auth0 to my app a few days ago so I cannot confirm that. I simply followed the quickstart instructions and i kept getting invalid state error with google and facebook. After seeing this issue I tried github and also custom signup with email and both work fine. It's just facebook and google that are failing (so far). Note that I am using my own app id key for facaebook but the auth0 dev one for google.

**Comment by stevehobbsdev** [comment]
@AntoLepejian Thanks - as a quick test can you revert the version of the SDK that you're pulling into your app to `1.2.4` and see if that resolves the issue for you? Just as a temporary measure to diagnose your issue.

**Comment by Junkern** [comment]
Just to comment: I also had the same issue (but with github) and using `1.2.4` fixed it for me.

**Comment by SenneDirkx** [comment]
I also have the React SPA quickstart running. Github and Twitter works great. Google & Facebook I get this same error.

**Comment by SenneDirkx** [comment]
Just wanted to add: changing to @auth0/auth0-spa-js@1.2.4 fixed it.

**Comment by SenneDirkx** [comment]
@stevehobbsdev `1.3.2` seems to have fixed it! Thanks a bunch.

**Comment by FreeVote** [comment]
Confirmed here too - Facebook login works as expected. 

Many thanks.

**Comment by AntoLepejian** [comment]
Can also confirm issue has been fixed

**Comment by danielres** [comment]
I can also confirm 1.3.2 fixes the problem.
:+1:

**Comment by stevehobbsdev** [comment]
Thanks for the feedback everyone, and for your help and patience while the issue was being resolved 🎉

**Comment by ionathanr** [comment]
Hi, i am using the Vue quickstart guide and i am still getting this error. Invalid state. Could anyone using Vue give some hints on how to overcome this?

**Comment by agersea** [comment]
I'm hitting this as well.  Authenticate using google, refresh the page, and the error logs.

I'm running Vue2, TS, auth0-spa-js 1.20.0.

Thank you!

**Comment by stevehobbsdev** [comment]
@agersea could you raise a new issue please so that this doesn't get lost, and provide clear repro steps, as I'm not able to reproduce what you're seeing but I might be missing something in your setup.

As you're using Vue, we now have a dedicated Vue SDK in beta, which could be worth migrating to in order to see if that solves your issue: https://github.com/auth0/auth0-vue

**Comment by agersea** [comment]
Thank you @stevehobbsdev, I believe the root cause is that I didn't remove the QSP from the redirect URL.  I'm working on this project today and will let you know as soon as I confirm the fix.

**Comment by agersea** [comment]
Confirmed, [reference](https://github.com/auth0/auth0-spa-js/issues/384)

I added `window.history.replaceState({}, document.title, window.location.pathname);` to my onRedirectCallback function.  Like so:

`Vue.use(
  Auth0Plugin,
  {
    domain: process.env.VUE_APP_AUTH_DOMAIN,
    clientId: process.env.VUE_APP_AUTH_CLIENT_ID,
    onRedirectCallback: (appState: any) => {
      // Fix goes here
      window.history.replaceState({}, document.title, window.location.pathname);
      router.push(
        appState && appState.targetUrl
          ? appState.targetUrl
          : window.location.pathname
      );
    },
  },
);`
