### ISSUE TITLE
Using Memory as a cache location prevents storing session across web applications on different subdomains

### ISSUE THREAD

**Issue by xepps** [auth0/auth0-spa-js#701]
### Describe the problem

Our platform is set up so that we have an authentication and onboarding application (let's call this service 'A') and other applications for our users to use (service 'B'). When a user visits service B and they are unauthenticated, they are redirected to service 'A', which uses Auth0 down the line to authenticate them. Once the session is created in service 'A' they are redirected back to service 'B'. 

When localstorage is set as the storage mechanism, this works fine, however, we want to use memory as the storage mechanism as it's more secure.

However, in `checkSession` there is first a check for the cookie `auth0.is.authenticated`. This cookie gets set in service 'A', but when the user is redirected back to service 'B', this service doesn't think the user is authenticated (even though we can silently get a token for them) because the cookie does not exist, so it redirects them back to 'A'. 

I think I understand this cookie is an optimisation to prevent the application keep checking for a token when it should already have a session, but it does break our flow for multi-app.

We are using the react wrapper by the way, but the issue occurs in here.

### What was the expected behavior?

We would expect the application to behave the same as if localstorage is set as the storage solution.

### Reproduction

- memory set as the storage solution
- 2 apps, (a) that logs into auth0 and redirects to (b) on success, and (b) that redirects to (a) when not logged in
- observe the redirects between the apps as (a) says it's authenticated, and (b) says it's not

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

No, as we are using the react wrapper unfortunately.

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:** 1.12.1
- **Which browsers have you tested in?** all browsers
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** @auth0/react (but it's definitely in here)

### Epilogue
Thanks for your help in advance with this issue. If we are doing anything wrong, please let us know.

**Comment by xepps** [comment]
It does appear this should be possible, see this:
https://community.auth0.com/t/sharing-session-between-2-web-apps-on-different-subdomains/39624/3

**Comment by stevehobbsdev** [comment]
Thanks @xepps - if it's just the `is.authenticated` cookie that's blocking your scenario, does it work if you call `getAccessTokenSilently` (discarding the return value) instead of `checkSession`? The latter just wraps the former with that cookie check.

Or if you're not calling `checkSession` directly, calling `getAccessTokenSilently` manually before your decision to redirect away to Service A. Calling this should rehydrate the cache regardless of that cookie being present or not.

**Comment by xepps** [comment]
Hey @stevehobbsdev! 

Yeah, so as an investigation we set a call off to `getAccessTokenSilently` in an effect before the application loaded. Unfortunately (and this may be because we are using the react wrapper), this does not set the auth0 client under the hood as logged in, but it does fetch the session and set the cookie, meaning that on the second loop back it picks up the cookie, checks the session, and sets us as authenticated. 

As another work around we literally set `document.cookie= 'auth0.is.authenticated=true;'` at the top of our `index.html` so that the cookie is always set (even if we aren't authenticated). This makes everything work as expected, although more inefficiently.

**Comment by stevehobbsdev** [comment]
@xepps Can you let me know which version of Auth0 React you're using? What you're describing sounds like something we fixed in 1.2, so we're just covering that off in case you have another scenario where that doesn't work.

https://github.com/auth0/auth0-react/releases/tag/v1.2.0
https://github.com/auth0/auth0-react/pull/146

**Comment by xepps** [comment]
Hi @stevehobbsdev Looks like we should update then! We are on version 1.1.0

**Comment by stevehobbsdev** [comment]
Great! Let me know if that fixes your issue.

**Comment by xepps** [comment]
@stevehobbsdev We've just given that a go and unfortunately that does not resolve our issue.

**Comment by adamjmcgrath** [comment]
Hi @xepps 

I've [created a branch](https://github.com/auth0/auth0-react/compare/gat-example) of the auth0-react playground - initialising with a call to `getAccessTokenSilently`

If you:

1. checkout the branch at https://github.com/auth0/auth0-react/compare/gat-example
2. Add your own `clientId` and `domain` to https://github.com/auth0/auth0-react/blob/fc74e7fc20830c01a8f6022d2b5651b9d9512af7/static/index.html#L91-L92
3. run the app using `npm start` and visit http://localhost:3000
4. login to auth0.com
5. Return to the app, confirm you're logged in by getting an access token, then delete your cookies (so you're logged in to auth0.com but not the app locally)
6. Refresh the page, then you should notice that you're logged in, even though you didn't have the `auth0.is.authenticated` set

Also attaching a video

https://user-images.githubusercontent.com/1299658/107518211-a7451e00-6ba6-11eb-90d3-16269066a086.mov

**Comment by xepps** [comment]
Hi @adamjmcgrath 

Yes, I believe the following shim would work as it forces the `getAccessTokenSilently` method to be called irregardless of there being a cookie set or not (but would set the cookie for the next time the page was visited).

```js
useEffect(() => {
    if (isLoading) return;
    (async () => {
        await getAccessTokenSilently();
    })();
}, [isLoading]);
```

Is this the suggested solution as a temporary measure, or a permanent fix?

**Comment by adamjmcgrath** [comment]
Hi @xepps - yep, this is our recommended solution to your use case

Also, my bad - you don't really need the `isLoading` check, since spa js doesn't allow concurrent authentication requests.

**Comment by xepps** [comment]
Ok. Thanks @adamjmcgrath

**Comment by stevehobbsdev** [comment]
Closing as this looks to be resolved - thanks for chipping in @adamjmcgrath
